### ISSUE TITLE
Update needed to Revision 12 from 2021

### ISSUE THREAD

**Issue by BenceSzalai** [datasets/unece-package-codes#4]
Apparently the dataset was last updated on Jul 29, 2016, while the related source of truth was last updated in 2021.
https://unece.org/trade/uncefact/cl-recommendations - see under Rec 21, Recommendation N°21 - Revision 12, last updated: 2021

Also it'd be good to indicate in the readme from which revision the data is, so it could be easier to track necessary updates in the future without comparing the whole dataset. Newer revisions typically only include additions, change or removal of a row is extremely rare.

**Comment by sabas** [comment]
Done :-)

**Comment by BenceSzalai** [comment]
Would it appear on https://datahub.io/core/unece-package-codes as well, or is that a separate task to publish there?

**Comment by sabas** [comment]
Hi @BenceSzalai see this https://datahub.io/blog/we-have-some-important-updates-re-datahub
cc @rufuspollock

**Comment by rufuspollock** [comment]
@BenceSzalai we are working on fixing it on datahub atm (it depends on a substantive backend change).

**Comment by BenceSzalai** [comment]
Cool, thanks for letting me know! Great project anyway, hope it'll be back to full feature soon!
